# Generated by Django 3.2.6 on 2021-08-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('hide_books ', 'Can hide books'), ('fuck boys', 'Can fuck boys'), ('fuck girls', 'Can fuck girls')]},
        ),
    ]
